Repository reactor/reactor-kafka, pull requests merged in 2020-05, with the labels that each got.

#142 Do not access ConsumerFlux's state from tests
  src/main/java/reactor/kafka/receiver/internals/ConsumerFlux.java
  src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java
  src/test/java/reactor/kafka/receiver/KafkaReceiverTest.java
  src/test/java/reactor/kafka/receiver/internals/ChaosConsumerFactory.java
  src/test/java/reactor/kafka/receiver/internals/TestableReceiver.java
Labels: type/chore

#143 Dispose `ConsumerFlux` on cancel/error
  src/main/java/reactor/kafka/receiver/internals/ConsumerFlux.java
  src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java
Labels: type/enhancement

#145 Introduce `ConsumerHandler` abstraction
  src/main/java/reactor/kafka/receiver/internals/ConsumerFlux.java
  src/main/java/reactor/kafka/receiver/internals/ConsumerHandler.java
  src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java
  src/test/java/reactor/kafka/receiver/internals/MockReceiverTest.java
  src/test/java/reactor/kafka/receiver/internals/TestableReceiver.java
Labels: type/enhancement

#148 Handle request signals in `ConsumerEventLoop`, remove `handleRequest`
  src/main/java/reactor/kafka/receiver/internals/ConsumerEventLoop.java
  src/main/java/reactor/kafka/receiver/internals/ConsumerHandler.java
  src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java
  src/test/java/reactor/kafka/receiver/internals/MockReceiverTest.java
Labels: type/enhancement

#151 Do not block when disposing the event loop
  build.gradle
  src/main/java/reactor/kafka/receiver/internals/ConsumerEventLoop.java
  src/main/java/reactor/kafka/receiver/internals/ConsumerHandler.java
  src/test/java/reactor/kafka/receiver/KafkaReceiverTest.java
  src/test/java/reactor/kafka/receiver/internals/MockReceiverTest.java
  src/test/java/reactor/kafka/util/ConsumerDelegate.java
Labels: type/bug

#152 Fix the request handling
  src/main/java/reactor/kafka/receiver/internals/ConsumerEventLoop.java
  src/main/java/reactor/kafka/receiver/internals/ConsumerHandler.java
  src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java
  src/main/java/reactor/kafka/receiver/internals/OperatorUtils.java
  src/test/java/reactor/kafka/receiver/KafkaReceiverTest.java
  src/test/java/reactor/kafka/receiver/internals/OperatorUtilsTest.java
Labels: type/enhancement

#153 CloseEvent Polishing
  src/main/java/reactor/kafka/receiver/internals/ConsumerEventLoop.java
Labels: type/enhancement
