Repository reactor/reactor-kafka, pull requests merged in 2024-10, with the labels that each got.

#396 GH-395: Add Dependabot support to the project
  .github/dependabot.yml
Labels: type/chore

#402 Regroup Dependabot updates
  .github/dependabot.yml
Labels: type/chores

#405 Fix MockReceiverTest#consumerMethods failure with reactor-core 3.5
  src/test/java/reactor/kafka/receiver/internals/MockReceiverTest.java
Labels: type/bug
